// ─────────────────────────────────────────────────────────────
// Lista curada de países + DDI (código internacional de telefone).
// Usada nos seletores de país do cadastro / confirmação de celular,
// para montar o número no formato E.164 (+DDI + número nacional).
//
// Brasil é o padrão. Para incluir mais países, basta adicionar aqui.
// (Códigos +1 de EUA/Canadá agrupados numa entrada só.)
// ─────────────────────────────────────────────────────────────
export type Pais = { nome: string; ddi: string; flag: string };

export const PAISES: Pais[] = [
  { nome: 'Brasil', ddi: '55', flag: '🇧🇷' },
  { nome: 'Portugal', ddi: '351', flag: '🇵🇹' },
  { nome: 'Estados Unidos / Canadá', ddi: '1', flag: '🇺🇸' },
  { nome: 'Argentina', ddi: '54', flag: '🇦🇷' },
  { nome: 'Uruguai', ddi: '598', flag: '🇺🇾' },
  { nome: 'Paraguai', ddi: '595', flag: '🇵🇾' },
  { nome: 'Chile', ddi: '56', flag: '🇨🇱' },
  { nome: 'Bolívia', ddi: '591', flag: '🇧🇴' },
  { nome: 'Peru', ddi: '51', flag: '🇵🇪' },
  { nome: 'Colômbia', ddi: '57', flag: '🇨🇴' },
  { nome: 'Equador', ddi: '593', flag: '🇪🇨' },
  { nome: 'Venezuela', ddi: '58', flag: '🇻🇪' },
  { nome: 'México', ddi: '52', flag: '🇲🇽' },
  { nome: 'Panamá', ddi: '507', flag: '🇵🇦' },
  { nome: 'Costa Rica', ddi: '506', flag: '🇨🇷' },
  { nome: 'Guatemala', ddi: '502', flag: '🇬🇹' },
  { nome: 'Honduras', ddi: '504', flag: '🇭🇳' },
  { nome: 'El Salvador', ddi: '503', flag: '🇸🇻' },
  { nome: 'Nicarágua', ddi: '505', flag: '🇳🇮' },
  { nome: 'Cuba', ddi: '53', flag: '🇨🇺' },
  { nome: 'Angola', ddi: '244', flag: '🇦🇴' },
  { nome: 'Moçambique', ddi: '258', flag: '🇲🇿' },
  { nome: 'Cabo Verde', ddi: '238', flag: '🇨🇻' },
  { nome: 'Espanha', ddi: '34', flag: '🇪🇸' },
  { nome: 'França', ddi: '33', flag: '🇫🇷' },
  { nome: 'Itália', ddi: '39', flag: '🇮🇹' },
  { nome: 'Alemanha', ddi: '49', flag: '🇩🇪' },
  { nome: 'Reino Unido', ddi: '44', flag: '🇬🇧' },
  { nome: 'Irlanda', ddi: '353', flag: '🇮🇪' },
  { nome: 'Países Baixos', ddi: '31', flag: '🇳🇱' },
  { nome: 'Bélgica', ddi: '32', flag: '🇧🇪' },
  { nome: 'Suíça', ddi: '41', flag: '🇨🇭' },
  { nome: 'Áustria', ddi: '43', flag: '🇦🇹' },
  { nome: 'Suécia', ddi: '46', flag: '🇸🇪' },
  { nome: 'Noruega', ddi: '47', flag: '🇳🇴' },
  { nome: 'Dinamarca', ddi: '45', flag: '🇩🇰' },
  { nome: 'Finlândia', ddi: '358', flag: '🇫🇮' },
  { nome: 'Polônia', ddi: '48', flag: '🇵🇱' },
  { nome: 'Rússia', ddi: '7', flag: '🇷🇺' },
  { nome: 'Ucrânia', ddi: '380', flag: '🇺🇦' },
  { nome: 'Grécia', ddi: '30', flag: '🇬🇷' },
  { nome: 'Turquia', ddi: '90', flag: '🇹🇷' },
  { nome: 'Israel', ddi: '972', flag: '🇮🇱' },
  { nome: 'Emirados Árabes Unidos', ddi: '971', flag: '🇦🇪' },
  { nome: 'Arábia Saudita', ddi: '966', flag: '🇸🇦' },
  { nome: 'Catar', ddi: '974', flag: '🇶🇦' },
  { nome: 'Índia', ddi: '91', flag: '🇮🇳' },
  { nome: 'China', ddi: '86', flag: '🇨🇳' },
  { nome: 'Japão', ddi: '81', flag: '🇯🇵' },
  { nome: 'Coreia do Sul', ddi: '82', flag: '🇰🇷' },
  { nome: 'Singapura', ddi: '65', flag: '🇸🇬' },
  { nome: 'Malásia', ddi: '60', flag: '🇲🇾' },
  { nome: 'Tailândia', ddi: '66', flag: '🇹🇭' },
  { nome: 'Indonésia', ddi: '62', flag: '🇮🇩' },
  { nome: 'Filipinas', ddi: '63', flag: '🇵🇭' },
  { nome: 'Vietnã', ddi: '84', flag: '🇻🇳' },
  { nome: 'Austrália', ddi: '61', flag: '🇦🇺' },
  { nome: 'Nova Zelândia', ddi: '64', flag: '🇳🇿' },
  { nome: 'África do Sul', ddi: '27', flag: '🇿🇦' },
  { nome: 'Nigéria', ddi: '234', flag: '🇳🇬' },
  { nome: 'Egito', ddi: '20', flag: '🇪🇬' },
  { nome: 'Marrocos', ddi: '212', flag: '🇲🇦' },
];

export const DDI_PADRAO = '55';
