'use client';
import { useState } from 'react'; import type { Employee } from '../data/mockData'; import { documents, trainings } from '../data/mockData'; import { DataTable, Panel, StatusBadge } from './RhUi';
const tabs=['Dados pessoais','Dados profissionais','Documentos','Férias e ausências','Treinamentos','Histórico','Observações'];
const personal=[['Nome completo','Ana Carolina Souza'],['CPF','123.456.789-00'],['RG','45.678.901-2'],['Data de nascimento','18/07/1994'],['Estado civil','Casada'],['Telefone','(11) 98821-4401'],['Email','ana.souza@avantalab.com.br'],['Endereço','Rua das Acácias, 120 — São Paulo/SP'],['Contato de emergência','Paulo Souza • (11) 97711-2200']];
const professional=[['Cargo','Analista Financeira'],['Departamento','Financeiro'],['Gestor','Marcos Lima'],['Data de admissão','12/01/2026'],['Tipo de contrato','CLT'],['Jornada','Seg–Sex • 08:00–17:00'],['Salário fictício','R$ 5.800,00'],['Centro de custo','CC-110'],['Unidade','São Paulo — Matriz'],['Período de experiência','12/01/2026 a 21/07/2026']];
export default function EmployeeProfile({employee}:{employee:Employee}){const [tab,setTab]=useState(0);return <div className="space-y-5"><section className="rounded-xl bg-white p-5 shadow-[0_2px_14px_rgba(15,23,42,.055)]"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid h-20 w-20 shrink-0 place-items-center rounded-full bg-[#dcebf3] text-xl font-semibold text-[#07355d]">{employee.initials}</span><div className="flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="text-2xl font-semibold text-slate-900">{employee.name}</h2><StatusBadge value={employee.status}/></div><p className="mt-1 text-sm text-slate-500">{employee.role} • {employee.department}</p><div className="mt-4 flex flex-wrap gap-x-7 gap-y-2 text-xs text-slate-500"><span><b className="text-slate-700">Admissão:</b> {employee.admission}</span><span><b className="text-slate-700">Gestor:</b> {employee.manager}</span><span><b className="text-slate-700">Contrato:</b> {employee.contract}</span></div></div><button className="min-h-10 rounded-lg border border-slate-200 px-4 text-sm text-slate-600">Editar ficha</button></div></section><div className="overflow-x-auto rounded-xl bg-white px-3 shadow-sm"><div className="flex min-w-max">{tabs.map((t,i)=><button key={t} onClick={()=>setTab(i)} className={`border-b-2 px-4 py-4 text-sm ${tab===i?'border-[#0c7190] font-medium text-[#0c567f]':'border-transparent text-slate-500'}`}>{t}</button>)}</div></div>
{tab<2&&<Panel title={tabs[tab]}><div className="grid gap-x-10 gap-y-5 md:grid-cols-2">{(tab===0?personal:professional).map(([label,value])=><div key={label} className={/Endereço|Contato|Período/.test(label)?'md:col-span-2':''}><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm text-slate-700">{employee.id==='ana-souza'?value: label==='Nome completo'?employee.name:value}</p></div>)}</div></Panel>}
{tab===2&&<Panel title="Documentos do colaborador"><DataTable headers={['Documento','Categoria','Envio','Validade','Status','Ação']} rows={documents.slice(0,5).map(d=>[d[0],d[2],d[3],d[4],<StatusBadge key="s" value={d[5]}/>,<button key="a" className="text-[#0c567f]">Visualizar</button>])}/></Panel>}
{tab===3&&<div className="grid gap-5 lg:grid-cols-3"><Panel title="Saldo atual"><p className="text-4xl font-semibold text-[#07355d]">18 <span className="text-sm font-normal text-slate-400">dias disponíveis</span></p><p className="mt-3 text-sm text-slate-500">Período aquisitivo: 12/01/2026 a 11/01/2027</p></Panel><Panel title="Férias"><p className="text-sm text-slate-600">Programadas: 01/08 a 12/08/2026</p><p className="mt-2 text-sm text-slate-600">Realizadas: nenhum período</p></Panel><Panel title="Ocorrências"><p className="text-sm text-slate-600">Faltas: 0 • Atestados: 1</p><p className="mt-2 text-sm text-slate-600">Afastamentos: 0</p></Panel></div>}
{tab===4&&<Panel title="Treinamentos"><DataTable headers={['Treinamento','Carga horária','Data','Validade','Status','Certificado']} rows={trainings.slice(0,3).map(t=>[t[0],t[2],t[4],t[5],<StatusBadge key="s" value={t[8]}/>,<button key="a" className="text-[#0c567f]">Visualizar</button>])}/></Panel>}
{tab===5&&<Panel title="Histórico profissional"><div className="ml-2 border-l border-slate-200 pl-6">{[['12/01/2026','Admissão registrada'],['05/02/2026','Documento enviado: contrato de trabalho'],['12/02/2026','Treinamento de integração concluído'],['30/04/2026','Alteração salarial registrada'],['02/07/2026','Férias programadas']].map(([date,text])=><div key={text} className="relative pb-6 last:pb-0"><span className="absolute -left-[29px] top-1 h-2.5 w-2.5 rounded-full bg-[#0c7190] ring-4 ring-white"/><p className="text-xs text-slate-400">{date}</p><p className="mt-1 text-sm text-slate-700">{text}</p></div>)}</div></Panel>}
{tab===6&&<Panel title="Observações internas" subtitle="Futuramente, somente usuários autorizados poderão visualizar este conteúdo."><textarea className="min-h-40 w-full rounded-lg border border-slate-200 p-4 text-sm outline-none" placeholder="Registre uma observação interna..."/><div className="mt-3 text-right"><button className="rounded-lg bg-[#0c567f] px-4 py-2 text-sm text-white">Simular anotação</button></div></Panel>}</div>}
