'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/app/lib/supabase';

export type DestinoBackup = 'local' | 'nuvem' | 'ambos';
type Conexao = { provedor: 'google_drive' | 'onedrive'; email?: string | null; ultimo_envio_em?: string | null } | null;
type ArquivoNuvem = { id: string; nome: string; tamanho: number; criadoEm: string };

async function cabecalhos() {
  const { data } = await supabase.auth.getSession();
  if (!data.session?.access_token) throw new Error('Sua sessão expirou. Entre novamente para continuar.');
  return { Authorization: `Bearer ${data.session.access_token}` };
}

const painel = 'fixed inset-0 z-[7100] flex items-center justify-center bg-slate-950/75 px-3 py-3';
function card(darkMode: boolean) { return `flex max-h-[calc(100dvh-24px)] w-full max-w-lg flex-col overflow-hidden rounded-2xl border shadow-2xl ${darkMode ? 'border-slate-700 bg-slate-900 text-white' : 'border-slate-200 bg-white text-slate-900'}`; }
function bytes(valor: number) { return valor > 1024 * 1024 ? `${(valor / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.ceil(valor / 1024))} KB`; }

export function DestinoBackupNuvemModal({ aberto, empresaId, darkMode, corPrimaria = '#003E73', origem, onFechar, onConfirmar }: { aberto: boolean; empresaId: string; darkMode: boolean; corPrimaria?: string; origem: 'web' | 'mobile'; onFechar: () => void; onConfirmar: (destino: DestinoBackup) => Promise<void> | void }) {
  const [conexao, setConexao] = useState<Conexao>(null); const [carregando, setCarregando] = useState(false); const [destino, setDestino] = useState<DestinoBackup>('local'); const [erro, setErro] = useState('');
  const carregar = async () => { if (!empresaId) return; setCarregando(true); setErro(''); try { const r = await fetch(`/api/backup-nuvem?empresaId=${encodeURIComponent(empresaId)}`, { headers: await cabecalhos() }); const json = await r.json(); if (!r.ok) throw new Error(json.mensagem); setConexao(json.conexao); } catch (e) { setErro(e instanceof Error ? e.message : 'Não foi possível consultar a conexão.'); } finally { setCarregando(false); } };
  useEffect(() => { if (aberto) void carregar(); }, [aberto, empresaId]);
  if (!aberto) return null;
  const conectar = async (provedor: 'google_drive' | 'onedrive') => { setCarregando(true); setErro(''); try { const r = await fetch('/api/backup-nuvem', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(await cabecalhos()) }, body: JSON.stringify({ acao: 'iniciar', empresaId, provedor, origem }) }); const json = await r.json(); if (!r.ok) throw new Error(json.mensagem); window.location.assign(json.url); } catch (e) { setErro(e instanceof Error ? e.message : 'Não foi possível iniciar a conexão.'); setCarregando(false); } };
  return <div className={painel} role="dialog" aria-modal="true" aria-labelledby="titulo-destino-backup"><section className={card(darkMode)}>
    <header className="shrink-0 px-5 py-4 text-white" style={{ backgroundColor: corPrimaria }}><p className="text-[10px] font-black uppercase tracking-[.18em] text-white/75">Backup seguro</p><h2 id="titulo-destino-backup" className="text-xl font-black">Onde salvar este backup?</h2></header>
    <div className="min-h-0 overflow-y-auto p-4">
      <p className={`text-sm font-semibold ${darkMode ? 'text-slate-300' : 'text-slate-600'}`}>A escolha vale somente para este backup. Seus dados continuam sob seu controle.</p>
      <div className="mt-4 grid gap-2">
        {([['local', 'Neste dispositivo', 'Baixa o arquivo Excel para o aparelho.'], ['nuvem', 'Conta conectada', conexao ? `Envia para ${conexao.provedor === 'google_drive' ? 'Google Drive' : 'OneDrive'}${conexao.email ? ` (${conexao.email})` : ''}.` : 'Conecte uma conta para usar esta opção.'], ['ambos', 'Nos dois lugares', 'Baixa no aparelho e envia uma cópia para a nuvem.']] as const).map(([id, titulo, texto]) => { const indisponivel = id !== 'local' && !conexao; return <label key={id} className={`flex cursor-pointer items-start gap-3 rounded-xl border p-3 transition ${destino === id ? 'border-cyan-500 bg-cyan-50 text-slate-900' : darkMode ? 'border-slate-700 text-slate-100' : 'border-slate-200'} ${indisponivel ? 'cursor-not-allowed opacity-55' : ''}`}><input type="radio" name="destino-backup" checked={destino === id} disabled={indisponivel || carregando} onChange={() => setDestino(id)} className="mt-1 h-4 w-4" style={{ accentColor: corPrimaria }} /><span><strong className="block text-sm">{titulo}</strong><span className={`mt-0.5 block text-xs font-semibold ${darkMode && destino !== id ? 'text-slate-400' : 'text-slate-500'}`}>{texto}</span></span></label>; })}
      </div>
      {!conexao && <div className={`mt-4 rounded-xl border p-3 ${darkMode ? 'border-slate-700 bg-slate-950/40' : 'border-slate-200 bg-slate-50'}`}><p className="text-xs font-black uppercase tracking-wide">Conectar uma conta</p><p className={`mt-1 text-xs font-semibold ${darkMode ? 'text-slate-400' : 'text-slate-600'}`}>Você será levado ao provedor escolhido para autorizar apenas a pasta de backups. Nunca informe sua senha ao AvantaLab.</p><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" disabled={carregando} onClick={() => void conectar('google_drive')} className="h-10 rounded-lg border border-slate-300 text-xs font-black text-slate-700 disabled:opacity-50">Google Drive</button><button type="button" disabled={carregando} onClick={() => void conectar('onedrive')} className="h-10 rounded-lg border border-slate-300 text-xs font-black text-slate-700 disabled:opacity-50">OneDrive</button></div></div>}
      {erro && <p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-xs font-bold text-red-700">{erro}</p>}
    </div>
    <footer className={`flex shrink-0 gap-2 border-t p-3 ${darkMode ? 'border-slate-700' : 'border-slate-200'}`}><button type="button" disabled={carregando} onClick={onFechar} className="h-11 flex-1 rounded-xl border border-slate-300 text-xs font-black uppercase">Cancelar</button><button type="button" disabled={carregando} onClick={() => void onConfirmar(destino)} className="h-11 flex-1 rounded-xl text-xs font-black uppercase text-white disabled:opacity-60" style={{ backgroundColor: corPrimaria }}>{carregando ? 'Preparando...' : 'Gerar backup'}</button></footer>
  </section></div>;
}

export function RestaurarDaNuvemModal({ aberto, empresaId, darkMode, corPrimaria = '#003E73', onFechar, onSelecionar }: { aberto: boolean; empresaId: string; darkMode: boolean; corPrimaria?: string; onFechar: () => void; onSelecionar: (arquivo: File) => Promise<void> | void }) {
  const [arquivos, setArquivos] = useState<ArquivoNuvem[]>([]); const [carregando, setCarregando] = useState(false); const [erro, setErro] = useState('');
  useEffect(() => { if (!aberto || !empresaId) return; setCarregando(true); setErro(''); void (async () => { try { const r = await fetch(`/api/backup-nuvem?acao=arquivos&empresaId=${encodeURIComponent(empresaId)}`, { headers: await cabecalhos() }); const json = await r.json(); if (!r.ok) throw new Error(json.mensagem); setArquivos(json.arquivos || []); } catch (e) { setErro(e instanceof Error ? e.message : 'Não foi possível abrir os backups em nuvem.'); } finally { setCarregando(false); } })(); }, [aberto, empresaId]);
  const escolher = async (item: ArquivoNuvem) => { setCarregando(true); setErro(''); try { const r = await fetch(`/api/backup-nuvem/arquivo?empresaId=${encodeURIComponent(empresaId)}&id=${encodeURIComponent(item.id)}&nome=${encodeURIComponent(item.nome)}`, { headers: await cabecalhos() }); if (!r.ok) { const json = await r.json().catch(() => ({})); throw new Error(json.mensagem || 'Não foi possível baixar o arquivo.'); } await onSelecionar(new File([await r.blob()], item.nome, { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })); } catch (e) { setErro(e instanceof Error ? e.message : 'Não foi possível abrir o backup.'); } finally { setCarregando(false); } };
  if (!aberto) return null;
  return <div className={painel} role="dialog" aria-modal="true" aria-labelledby="titulo-restaurar-nuvem"><section className={card(darkMode)}><header className="shrink-0 px-5 py-4 text-white" style={{ backgroundColor: corPrimaria }}><p className="text-[10px] font-black uppercase tracking-[.18em] text-white/75">Restauração</p><h2 id="titulo-restaurar-nuvem" className="text-xl font-black">Backup da conta conectada</h2></header><div className="min-h-0 overflow-y-auto p-4">{carregando && <p className="text-sm font-semibold">Carregando backups…</p>}{!carregando && !erro && arquivos.length === 0 && <p className="text-sm font-semibold">Nenhum backup Excel foi encontrado na pasta do AvantaLab.</p>}{arquivos.map((item) => <button type="button" key={item.id} disabled={carregando} onClick={() => void escolher(item)} className={`mb-2 flex w-full items-center justify-between gap-3 rounded-xl border p-3 text-left ${darkMode ? 'border-slate-700 hover:bg-slate-800' : 'border-slate-200 hover:bg-slate-50'}`}><span className="min-w-0"><strong className="block truncate text-sm">{item.nome}</strong><span className="text-xs font-semibold opacity-70">{new Date(item.criadoEm).toLocaleString('pt-BR')} · {bytes(item.tamanho)}</span></span><span aria-hidden="true">›</span></button>)}{erro && <p role="alert" className="rounded-lg bg-red-50 p-3 text-xs font-bold text-red-700">{erro}</p>}</div><footer className={`shrink-0 border-t p-3 ${darkMode ? 'border-slate-700' : 'border-slate-200'}`}><button type="button" onClick={onFechar} className="h-11 w-full rounded-xl border border-slate-300 text-xs font-black uppercase">Fechar</button></footer></section></div>;
}
