export type FiscalDocumentType = 'nfe' | 'nfce' | 'nfse';
export type FiscalRegistrationStatus = 'Não configurado' | 'Pendente' | 'Homologação' | 'Produção';
export type FiscalNfseRouteMode = 'Automática' | 'SEFIN Nacional' | 'Emissor municipal';
export type FiscalCscStatus = 'Não configurado' | 'Pendente' | 'Configurado';
export type FiscalDocumentRegistration = { enabled: boolean; registrationStatus: FiscalRegistrationStatus; series: string };
export type FiscalEstablishment = { id: string; label: string; kind: 'Matriz' | 'Filial'; active: boolean; legalName: string; document: string; uf: string; city: string; cityCode: string; cep: string; street: string; number: string; complement: string; district: string; phone: string; taxRegime: string; stateRegistration: string; municipalRegistration: string; documents: { nfe: FiscalDocumentRegistration; nfce: FiscalDocumentRegistration & { cscStatus: FiscalCscStatus }; nfse: FiscalDocumentRegistration & { routeMode: FiscalNfseRouteMode } } };
export type FiscalIssuerRegistry = { version: 2; reference: string; defaultEstablishmentId: string; establishments: FiscalEstablishment[] };
export type FiscalIssuerRoute = { documentType: FiscalDocumentType; authority: string; routeMode: string; environment: 'Homologação'; contingency: string; readyForHomologation: boolean; blockers: string[]; explanation: string };
export type FiscalIssuerSelectionSnapshot = { establishmentId: string; label: string; kind: 'Matriz' | 'Filial'; legalName: string; document: string; uf: string; city: string; cityCode: string; cep: string; street: string; number: string; complement: string; district: string; phone: string; taxRegime: string; stateRegistration: string; municipalRegistration: string; documentType: FiscalDocumentType; registrationStatus: FiscalRegistrationStatus; series: string; cscStatus?: FiscalCscStatus; nfseRouteMode?: FiscalNfseRouteMode; routeReference: string; authorityRoute: string; contingency: string; routeReadyForHomologation: boolean; routeBlockers: string[] };
export const FISCAL_ISSUER_ROUTING_REFERENCE: string;
export const FISCAL_REGISTRATION_STATUSES: FiscalRegistrationStatus[];
export const FISCAL_NFSE_ROUTE_MODES: FiscalNfseRouteMode[];
export const FISCAL_CSC_STATUSES: FiscalCscStatus[];
export function createFiscalEstablishmentFromCompany(company?: Record<string, unknown>, index?: number): FiscalEstablishment;
export function createFiscalIssuerRegistry(company?: Record<string, unknown>): FiscalIssuerRegistry;
export function normalizeFiscalIssuerRegistry(value: unknown, company?: Record<string, unknown>): FiscalIssuerRegistry;
export function resolveFiscalIssuerRoute(establishment: FiscalEstablishment, documentType: FiscalDocumentType): FiscalIssuerRoute;
export function createFiscalIssuerSelectionSnapshot(establishment: FiscalEstablishment | undefined, documentType: FiscalDocumentType): FiscalIssuerSelectionSnapshot | undefined;
export function resolveFiscalIssuerSelection(value: unknown, documentType: FiscalDocumentType, preferredEstablishmentId?: string, company?: Record<string, unknown>): { valid: boolean; errors: string[]; warnings: string[]; establishment?: FiscalEstablishment & { routes: Record<FiscalDocumentType, FiscalIssuerRoute>; enabledDocuments: FiscalDocumentType[]; readyDocuments: FiscalDocumentType[] }; route?: FiscalIssuerRoute; snapshot?: FiscalIssuerSelectionSnapshot };
export function evaluateFiscalIssuerRegistry(value: unknown, company?: Record<string, unknown>): { registry: FiscalIssuerRegistry; establishments: Array<FiscalEstablishment & { routes: Record<FiscalDocumentType, FiscalIssuerRoute>; enabledDocuments: FiscalDocumentType[]; readyDocuments: FiscalDocumentType[] }>; defaultEstablishment?: FiscalEstablishment & { routes: Record<FiscalDocumentType, FiscalIssuerRoute>; enabledDocuments: FiscalDocumentType[]; readyDocuments: FiscalDocumentType[] }; activeCount: number; enabledRouteCount: number; readyRouteCount: number };
export function validateFiscalIssuerRegistry(value: unknown, company?: Record<string, unknown>): ReturnType<typeof evaluateFiscalIssuerRegistry> & { valid: boolean; errors: string[]; warnings: string[] };
