export type FiscalArtifactType = 'processed_xml' | 'danfe_pdf';
export type FiscalStatusArtifact = { id: string; artifactType: FiscalArtifactType; available: true };
export type FiscalEmissionStatus = {
  id: string;
  version: number;
  documentType: string;
  model: string;
  environment: string;
  state: string;
  stateLabel: string;
  series: string;
  number: number;
  accessKey: string;
  statusCode: string;
  statusReason: string;
  protocolNumber: string;
  canceledAt?: string;
  cancellationProtocol?: string;
  cancellationStatusCode?: string;
  updatedAt: string;
  authorized: boolean;
  finalDocumentReady: boolean;
  recoveryPending: boolean;
  needsTechnicalAttention: boolean;
  actionRequired: boolean;
  recommendedAction: 'review_emission' | 'review_fiscal_data' | '';
  recommendedActionLabel: string;
  recommendedActionMessage: string;
  artifacts: readonly FiscalStatusArtifact[];
};
export type FiscalPreparedEmission = {
  emissionId: string;
  draftId: string;
  orderId: string;
  documentType: 'nfe';
  model: '55';
  environment: 'homologacao';
  state: string;
  version: number;
  reused: boolean;
};
export type FiscalCertificateStatus = Readonly<{
  status: 'unavailable' | 'pending_validation' | 'active';
  mode: string;
  validFrom: string;
  validTo: string;
  installedAt: string;
  fingerprintEnding: string;
  certificateInstalled: boolean;
  certificateActive: boolean;
  fiscalConnectionChecked: boolean;
  fiscalConnectionAvailable: boolean;
  validationChecked: boolean;
  validationCheckedAt: string;
  blockers: readonly string[];
  sensitiveMaterialReturned: false;
  originalPasswordStored?: false;
}>;
export type FiscalExecutionReadiness = Readonly<{
  environment: 'homologacao';
  statusOnly: boolean;
  workflowEnabled: boolean;
  durableStorageReady: boolean;
  certificateRuntimeReady: boolean;
  statusServiceReady: boolean;
  authorizationReady: boolean;
  returnServiceReady: boolean;
  orchestratorReady: boolean;
  transmissionAllowed: boolean;
  productionTransmissionAllowed: false;
}>;

export const FISCAL_STATUS_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_STATUS_REQUEST_V1';
export const FISCAL_STATUS_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_STATUS_RESPONSE_V1';
export const FISCAL_DOWNLOAD_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_DOWNLOAD_REQUEST_V1';
export const FISCAL_DOWNLOAD_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_DOWNLOAD_RESPONSE_V1';
export const FISCAL_PREPARE_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_PREPARE_REQUEST_V1';
export const FISCAL_PREPARE_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_PREPARE_RESPONSE_V1';
export const FISCAL_VALIDATE_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_VALIDATE_REQUEST_V1';
export const FISCAL_VALIDATE_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_VALIDATE_RESPONSE_V1';
export const FISCAL_NUMBER_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_NUMBER_REQUEST_V1';
export const FISCAL_NUMBER_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_NUMBER_RESPONSE_V1';
export const FISCAL_SIGNING_READINESS_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_SIGNING_READINESS_REQUEST_V1';
export const FISCAL_SIGNING_READINESS_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_SIGNING_READINESS_RESPONSE_V1';
export const FISCAL_SIGN_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_SIGN_REQUEST_V1';
export const FISCAL_SIGN_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_SIGN_RESPONSE_V1';
export const FISCAL_ISSUE_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_ISSUE_REQUEST_V1';
export const FISCAL_ISSUE_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_ISSUE_RESPONSE_V1';
export const FISCAL_CORRECTION_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_CORRECTION_REQUEST_V1';
export const FISCAL_CORRECTION_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_CORRECTION_RESPONSE_V1';
export const FISCAL_CANCELLATION_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_CANCELLATION_REQUEST_V1';
export const FISCAL_CANCELLATION_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_CANCELLATION_RESPONSE_V1';
export const FISCAL_CERTIFICATE_STATUS_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_CERTIFICATE_STATUS_REQUEST_V1';
export const FISCAL_CERTIFICATE_STATUS_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_CERTIFICATE_STATUS_RESPONSE_V1';
export const FISCAL_CERTIFICATE_INSTALL_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_CERTIFICATE_INSTALL_REQUEST_V1';
export const FISCAL_CERTIFICATE_INSTALL_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_CERTIFICATE_INSTALL_RESPONSE_V1';
export const FISCAL_CERTIFICATE_ACTIVATE_REQUEST_TYPE: 'AVANTALAB_VENDAS_FISCAL_CERTIFICATE_ACTIVATE_REQUEST_V1';
export const FISCAL_CERTIFICATE_ACTIVATE_RESPONSE_TYPE: 'AVANTALAB_VENDAS_FISCAL_CERTIFICATE_ACTIVATE_RESPONSE_V1';
export function createFiscalStatusRequest(input?: { requestId?: unknown; emissionId?: unknown }): Readonly<{ type: typeof FISCAL_STATUS_REQUEST_TYPE; requestId: string; emissionId: string }> | null;
export function createFiscalDownloadRequest(input?: { requestId?: unknown; artifactId?: unknown; artifactType?: unknown }): Readonly<{ type: typeof FISCAL_DOWNLOAD_REQUEST_TYPE; requestId: string; artifactId: string; artifactType: FiscalArtifactType }> | null;
export function createFiscalPrepareRequest(input?: { requestId?: unknown; draftId?: unknown }): Readonly<{ type: typeof FISCAL_PREPARE_REQUEST_TYPE; requestId: string; draftId: string }> | null;
export function createFiscalValidateRequest(input?: { requestId?: unknown; draftId?: unknown }): Readonly<{ type: typeof FISCAL_VALIDATE_REQUEST_TYPE; requestId: string; draftId: string }> | null;
export function createFiscalNumberRequest(input?: { requestId?: unknown; emissionId?: unknown; expectedVersion?: unknown }): Readonly<{ type: typeof FISCAL_NUMBER_REQUEST_TYPE; requestId: string; emissionId: string; expectedVersion: number }> | null;
export function createFiscalSigningReadinessRequest(input?: { requestId?: unknown; emissionId?: unknown; expectedVersion?: unknown }): Readonly<{ type: typeof FISCAL_SIGNING_READINESS_REQUEST_TYPE; requestId: string; emissionId: string; expectedVersion: number }> | null;
export function createFiscalSignRequest(input?: { requestId?: unknown; emissionId?: unknown; expectedVersion?: unknown }): Readonly<{ type: typeof FISCAL_SIGN_REQUEST_TYPE; requestId: string; emissionId: string; expectedVersion: number }> | null;
export function createFiscalIssueRequest(input?: { requestId?: unknown; emissionId?: unknown; expectedVersion?: unknown }): Readonly<{ type: typeof FISCAL_ISSUE_REQUEST_TYPE; requestId: string; emissionId: string; expectedVersion: number }> | null;
export function createFiscalCorrectionRequest(input?: { requestId?: unknown; emissionId?: unknown; expectedVersion?: unknown; rejectedStatusCode?: unknown; items?: ReadonlyArray<{ sku?: unknown; ncm?: unknown }> }): Readonly<{ type: typeof FISCAL_CORRECTION_REQUEST_TYPE; requestId: string; emissionId: string; expectedVersion: number; rejectedStatusCode: string; items: ReadonlyArray<Readonly<{ sku: string; ncm: string }>> }> | null;
export function createFiscalCancellationRequest(input?: { requestId?: unknown; emissionId?: unknown; expectedVersion?: unknown; justification?: unknown }): Readonly<{ type: typeof FISCAL_CANCELLATION_REQUEST_TYPE; requestId: string; emissionId: string; expectedVersion: number; justification: string }> | null;
export function createFiscalCertificateStatusRequest(input?: { requestId?: unknown }): Readonly<{ type: typeof FISCAL_CERTIFICATE_STATUS_REQUEST_TYPE; requestId: string }> | null;
export function createFiscalCertificateInstallRequest(input?: { requestId?: unknown; certificate?: File | null; passphrase?: unknown }): Readonly<{ type: typeof FISCAL_CERTIFICATE_INSTALL_REQUEST_TYPE; requestId: string; certificate: File; passphrase: string }> | null;
export function createFiscalCertificateActivateRequest(input?: { requestId?: unknown }): Readonly<{ type: typeof FISCAL_CERTIFICATE_ACTIVATE_REQUEST_TYPE; requestId: string }> | null;
export function parseFiscalCertificateStatusResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; message: string; certificate: FiscalCertificateStatus; execution: FiscalExecutionReadiness | null }> | null;
export function parseFiscalCertificateInstallResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; message: string; certificate: FiscalCertificateStatus; execution: FiscalExecutionReadiness | null }> | null;
export function parseFiscalCertificateActivateResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; message: string; certificate: FiscalCertificateStatus; execution: FiscalExecutionReadiness | null }> | null;
export function normalizeFiscalEmissionStatus(value: unknown): Readonly<FiscalEmissionStatus> | null;
export function parseFiscalStatusResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; emission: FiscalEmissionStatus }> | null;
export function parseFiscalDownloadResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; download: Readonly<{ url: string; expiresAt: string; filename: string; contentType: 'application/xml' | 'application/pdf' }> }> | null;
export function parseFiscalPrepareResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; emission: Readonly<FiscalPreparedEmission> }> | null;
export type FiscalValidatedEmission = FiscalPreparedEmission & Readonly<{ state: 'prepared'; schemaValid: true; candidateSeries: string; candidateNumber: number; numberReserved: false; certificateInspected: false; signed: false; transmitted: false }>;
export function parseFiscalValidateResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; emission: Readonly<FiscalValidatedEmission> }> | null;
export type FiscalNumberedEmission = FiscalPreparedEmission & Readonly<{ state: 'number_reserved'; series: string; number: number; numberReserved: true; certificateInspected: false; signed: false; transmitted: false }>;
export function parseFiscalNumberResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; emission: Readonly<FiscalNumberedEmission> }> | null;
export type FiscalSigningReadyEmission = FiscalPreparedEmission & Readonly<{ state: 'number_reserved'; series: string; number: number; documentReadyForA1Signature: true; schemaValid: true; realCertificateInspected: false; realSignatureAttempted: false; signed: false; persisted: false; transmitted: false; xmlReturned: false; sensitiveMaterialReturned: false }>;
export function parseFiscalSigningReadinessResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; emission: Readonly<FiscalSigningReadyEmission> }> | null;
export type FiscalSignedEmission = Readonly<{ emissionId: string; documentType: 'nfe'; model: '55'; environment: 'homologacao'; state: 'signed'; version: number; series: string; number: number; signed: true; persisted: true; artifactRegistered: true; realCertificateInspected: true; signatureVerified: true; signedXsdValid: true; transmitted: false; signedContentReturned: false; sensitiveMaterialReturned: false }>;
export function parseFiscalSignResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; emission: FiscalSignedEmission }> | null;
export type FiscalIssuedEmission = Readonly<{ emissionId: string; documentType: 'nfe'; model: '55'; environment: 'homologacao'; state: 'authorized' | 'processing' | 'rejected'; version: number; series: string; number: number; signed: true; persisted: true; submitted: true; transmitted: true; authorized: boolean; processing: boolean; rejected: boolean; statusCode: string; statusReason: string; protocolStored: boolean; receiptConsultationPending: boolean; externalContentReturned: false; sensitiveMaterialReturned: false }>;
export function parseFiscalIssueResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; emission: FiscalIssuedEmission }> | null;
export type FiscalCorrectedEmission = Readonly<{ emissionId: string; draftId: string; orderId: string; state: 'number_reserved'; version: number; series: string; number: number; correctionRevision: number; correctionPrepared: true; sameNumberPreserved: true; previousAttemptPreserved: true; requiresNewSignature: true; automaticTransmission: false; certificateInspected: false; signed: false; transmitted: false }>;
export function parseFiscalCorrectionResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; emission: FiscalCorrectedEmission }> | null;
export type FiscalCanceledEmission = Readonly<{ emissionId: string; state: 'canceled'; version: number; series: string; number: number; cancellationStatusCode: '135' | '155'; cancellationProtocol: string; canceledAt: string; canceled: true; eventStored: true; transmitted: true; originalAuthorizationPreserved: true; externalContentReturned: false; sensitiveMaterialReturned: false }>;
export function parseFiscalCancellationResponse(data: unknown): Readonly<{ requestId: string; ok: false; message: string } | { requestId: string; ok: true; emission: FiscalCanceledEmission }> | null;
export function fiscalStatusPresentation(status: FiscalEmissionStatus): Readonly<{ label: string; tone: 'success' | 'danger' | 'info' | 'warning'; detail: string }>;
