export type TaxProfileGroup = 'identificacao' | 'tributacao' | 'reforma';
export type CatalogTaxProfile = {
  fiscalProfileVersion: string;
  fiscalReviewedAt: string;
  fiscalReviewedBy: string;
  fiscalOriginCode: string;
  taxableUnit: string;
  fiscalBenefitCode: string;
  cfopInternal: string;
  cfopInterstate: string;
  icmsCode: string;
  icmsRate: number;
  pisCst: string;
  pisRate: number;
  cofinsCst: string;
  cofinsRate: number;
  ipiApplicable: boolean;
  ipiCst: string;
  ipiLegalCode: string;
  ipiRate: number;
  cestRequired: boolean;
  stApplicable: boolean;
  stBaseMode: string;
  stMvaRate: number;
  stIcmsRate: number;
  stBaseReductionRate: number;
  approximateFederalTaxRate: number;
  approximateStateTaxRate: number;
  nfeOverrideEnabled: boolean;
  nfeCfopInternal: string;
  nfeCfopInterstate: string;
  nfeIcmsCode: string;
  nfePisCst: string;
  nfeCofinsCst: string;
  nfceOverrideEnabled: boolean;
  nfceCfop: string;
  nfceIcmsCode: string;
  nfcePisCst: string;
  nfceCofinsCst: string;
  nationalServiceCode: string;
  serviceIncidenceMode: string;
  issWithheldDefault: boolean;
  ibsCbsCst: string;
  ibsCbsClassification: string;
  ibsCbsOperationIndicator: string;
  selectiveTaxCode: string;
};
export const TAX_PROFILE_REFERENCE: '2026.08';
export const catalogTaxProfileDefaults: Readonly<CatalogTaxProfile>;
export function normalizeCatalogTaxProfile<T extends Record<string, unknown>>(item: T): T & CatalogTaxProfile;
export function evaluateCatalogTaxProfile(item: Record<string, unknown>): {
  profile: Record<string, unknown> & CatalogTaxProfile;
  checks: Array<{ key: string; label: string; ready: boolean; group: TaxProfileGroup; detail: string }>;
  coreReady: boolean;
  reformReady: boolean;
  completion: number;
  status: string;
};
