import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const acesso = readFileSync('app/api/modulos/acesso/route.ts', 'utf8');
const gestao = readFileSync('app/gestao/page.tsx', 'utf8');
const cliente = readFileSync('app/projetos/ProjetosClient.tsx', 'utf8');
const workspace = readFileSync('app/projetos/components/ProjectWorkspace.tsx', 'utf8');
const mapa = readFileSync('app/projetos/components/MapCanvas.tsx', 'utf8');
const nodeCard = readFileSync('app/projetos/components/ProjectNodeCard.tsx', 'utf8');
const kanban = readFileSync('app/projetos/components/KanbanView.tsx', 'utf8');
const estilos = readFileSync('app/projetos/projetos.module.css', 'utf8');
const ajustes = readFileSync('app/api/modulos/projetos/ajustes/route.ts', 'utf8');
const inicioProjetos = readFileSync('app/projetos/components/ProjectHome.tsx', 'utf8');

test('AvantaProjetos recebe o tema salvo no perfil, sem depender do sistema operacional', () => {
  assert.match(acesso, /select\('cor_primaria, dark_mode'\)/);
  assert.match(acesso, /temaEscuro: configuracao\?\.dark_mode === true/);
  assert.match(gestao, /setDarkMode\(config\.dark_mode === true\)/);
  assert.match(gestao, /darkMode,\n\s*duplicadosAtivo,/);
  assert.match(cliente, /access\.empresa\.temaEscuro \? styles\.darkTheme/);
  assert.match(estilos, /\.darkTheme \{[\s\S]*color-scheme: dark/);
  assert.doesNotMatch(estilos, /prefers-color-scheme/);
  assert.match(estilos, /\.darkTheme \.moduleLogo \{ filter: brightness\(0\) invert\(1\)/);
  assert.match(cliente, /access\.empresa\.temaEscuro \? 'ON' : 'OFF'/);
  assert.match(estilos, /\.settingsSection \{ display: flex; align-items: center; justify-content: space-between; gap: 10px;/);
  assert.match(estilos, /\.settingsThemeSwitch \{ display: inline-flex; width: 104px; min-width: 104px;/);
  assert.match(cliente, /TelaCarregandoAcesso/);
  assert.match(cliente, /Ajustes do AvantaProjetos/);
  assert.match(cliente, /Voltar ao início do AvantaLab/);
  assert.match(cliente, /‹<\/span> Início/);
  assert.match(cliente, /const proximoAcesso = \{ \.\.\.access, empresa: \{ \.\.\.access\.empresa, temaEscuro \} \}/);
  assert.doesNotMatch(cliente, /Atualizando…/);
  assert.match(ajustes, /autenticarPerfilCobranca\(request, empresaId, true\)/);
  assert.match(ajustes, /update\(\{ dark_mode: temaEscuro \}\)/);
});

test('modo de foco do mapa oculta os cabeçalhos e preserva o retorno flutuante', () => {
  assert.match(workspace, /mapaEmFoco/);
  assert.match(workspace, /Ocultar cabeçalho/);
  assert.match(workspace, /Exibir cabeçalho do mapa/);
  assert.match(workspace, /proximaVisualizacao !== 'mapa'\) onMapaEmFocoChange\(false\)/);
  assert.match(workspace, /const requestDeleteNode = useCallback/);
  assert.match(workspace, /const \[deleteStep, setDeleteStep\] = useState<'choice' \| 'successor'>\('choice'\)/);
  assert.match(workspace, /Excluir nós conectados/);
  assert.match(workspace, /setDeleteStep\('successor'\)/);
  assert.match(workspace, /const confirmDeleteConnected = useCallback/);
  assert.match(workspace, /onClick=\{confirmDelete\} disabled=\{!replacementNodeId\}>Excluir<\/button>/);
  assert.match(workspace, /action: 'Nó removido'/);
  assert.match(workspace, /getDescendantIds\(project\.nodes, deleteNode\.id\)/);
  assert.match(workspace, /const removeConnection = useCallback/);
  assert.match(workspace, /onDeleteConnection=\{removeConnection\}/);
  assert.match(workspace, /action: 'Relação removida'/);
  assert.match(workspace, /Os cards foram mantidos/);
  assert.match(cliente, /Ajustes do AvantaProjetos/);
  assert.match(estilos, /\.mapFocusMode \.moduleHeader \{ display: none/);
  assert.match(estilos, /\.mapFocusMode \.workspaceHeader, \.mapFocusMode \.workspaceToolbar \{ display: none/);
  assert.match(estilos, /\.mapFocusMode \.workspace \{ height: 100dvh; min-height: 0; grid-template-rows: minmax\(0, 1fr\)/);
  assert.match(estilos, /\.mapFocusMode \.workspaceContent, \.mapFocusMode \.primaryView, \.mapFocusMode \.canvas \{ height: 100%; min-height: 0/);
  assert.match(estilos, /\.mapFocusToggleFloating \{ position: fixed/);
  assert.match(estilos, /\.edgeLine \{ fill: none; stroke: #879aa7; stroke-width: 2\.2; \}/);
  assert.doesNotMatch(estilos, /\.edgeLine \{[^}]*transition:/);
  assert.match(estilos, /\.root \.dangerButton \{ color: #fff; background: var\(--danger\); \}/);
  assert.match(estilos, /\.deleteNodeSelect select \{ width: 100%; min-height: 46px; border: 1px solid var\(--border\);/);
  assert.match(mapa, /x: drag\.origin\.x \+ \(event\.clientX - drag\.x\) \/ viewport\.scale, y: drag\.origin\.y \+ \(event\.clientY - drag\.y\) \/ viewport\.scale/);
  assert.doesNotMatch(mapa, /Math\.max\(0, drag\.origin\.y/);
  assert.match(nodeCard, /node\.description && <p className=\{styles\.nodeDescription\}>\{node\.description\}<\/p>/);
  assert.match(estilos, /\.mapNode \{[^}]*height: 132px/);
  assert.match(mapa, /Cores pré-definidas/);
  assert.match(mapa, /onColorPresetsChange/);
  assert.match(estilos, /\.colorPalette \{ display: flex; align-items: center; gap: 8px;/);
  assert.match(estilos, /\.presetColor, \.presetColorEditor \{[^}]*background: repeating-conic-gradient\([^}]*6px 6px; cursor: pointer;/);
  assert.doesNotMatch(estilos, /\.presetColor, \.presetColorEditor \{[^}]*background:[^}]*!important/);
  assert.match(inicioProjetos, /Icon name="people" size=\{16\} \/> Participantes/);
  assert.match(inicioProjetos, /title="Participantes" description="Cadastre pessoas para atribuí-las a projetos e tarefas\."/);
  assert.match(inicioProjetos, /participantManagerList/);
  assert.match(inicioProjetos, /id="edit-participant-registration"/);
  assert.match(inicioProjetos, /if \(editingProject\) setEditForm/);
  assert.match(estilos, /\.peopleChecks input\[type="checkbox"\] \{ width: 16px; height: 16px; min-height: 0; flex: 0 0 16px;/);
  assert.match(inicioProjetos, /import Tooltip from '@\/app\/components\/Tooltip';/);
  assert.match(inicioProjetos, /texto=\{person\.name\} posicao="top" wrapperClassName=\{styles\.avatarTooltip\}/);
  assert.match(nodeCard, /texto=\{person\.name\} posicao="top" wrapperClassName=\{styles\.avatarTooltip\}/);
  assert.match(kanban, /texto=\{person\.name\} posicao="top" wrapperClassName=\{styles\.avatarTooltip\}/);
  assert.match(mapa, /import Tooltip from '@\/app\/components\/Tooltip';/);
  assert.match(mapa, /<Tooltip texto="Adicionar filho \(Tab\)" posicao="bottom">/);
  assert.doesNotMatch(mapa, /title="Adicionar filho \(Tab\)"/);
  assert.match(estilos, /\.moduleExit span \{ display: inline-flex; height: 1em; align-items: center; font-size: 18px; font-weight: 400; line-height: 1; \}/);
});
